### ISSUE TITLE
Panic - `item header should be read only inside an existing sequence`

### ISSUE THREAD

**Issue by qarmin** [Enet4/dicom-rs#547]
Code
```
fn check_file(path: &str) {
    let Ok(file_content) = fs::read(path) else {
        return;
    };
    let cursor = std::io::Cursor::new(file_content);
    let Ok(res) = from_reader(cursor) else {
        return;
    };
    let mut item_to_dump = Vec::new();
    let _ = DumpOptions::new().dump_object_to(&mut item_to_dump, &res);
    // let _ = dicom_json::to_string(&res);
    let mut item_to_dump = Vec::new();
    let _ = res.write_dataset(&mut item_to_dump);
}
```
crash
```
thread 'main' panicked at /home/rafal/.cargo/git/checkouts/dicom-rs-165e2a1669724caa/4876a59/parser/src/dataset/read.rs:284:38:
item header should be read only inside an existing sequence
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_display
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/panicking.rs:264:5
   3: core::option::expect_failed
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/option.rs:2030:5
   4: core::option::Option<T>::expect
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/option.rs:933:21
   5: <dicom_parser::dataset::read::DataSetReader<S> as core::iter::traits::iterator::Iterator>::next
             at /home/rafal/.cargo/git/checkouts/dicom-rs-165e2a1669724caa/4876a59/parser/src/dataset/read.rs:284:38
   6: <&mut I as core::iter::traits::iterator::Iterator>::next
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/iter/traits/iterator.rs:4110:9
   7: dicom_object::mem::InMemDicomObject<D>::build_encapsulated_data
             at /home/rafal/.cargo/git/checkouts/dicom-rs-165e2a1669724caa/4876a59/object/src/mem.rs:1935:22
   8: dicom_object::mem::InMemDicomObject<D>::build_object
             at /home/rafal/.cargo/git/checkouts/dicom-rs-165e2a1669724caa/4876a59/object/src/mem.rs:1855:33
   9: dicom_object::mem::<impl dicom_object::FileDicomObject<dicom_object::mem::InMemDicomObject<D>>>::from_reader_with_all_options
             at /home/rafal/.cargo/git/checkouts/dicom-rs-165e2a1669724caa/4876a59/object/src/mem.rs:477:23
  10: dicom_object::file::OpenFileOptions<D,T>::from_reader
             at /home/rafal/.cargo/git/checkouts/dicom-rs-165e2a1669724caa/4876a59/object/src/file.rs:151:9
  11: dicom_object::file::from_reader
             at /home/rafal/.cargo/git/checkouts/dicom-rs-165e2a1669724caa/4876a59/object/src/file.rs:20:28
  12: dicom::check_file
             at /home/rafal/Projekty/Rust/run_command_for_every_file/src/crates/dicom/src/main.rs:32:19
  13: dicom::main
             at /home/rafal/Projekty/Rust/run_command_for_every_file/src/crates/dicom/src/main.rs:23:9
  14: core::ops::function::FnOnce::call_once
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)

```

file - [crash-4a8e7d7aaaef78b4761d91f1788d14cac21c3fcc.zip](https://github.com/user-attachments/files/16402330/crash-4a8e7d7aaaef78b4761d91f1788d14cac21c3fcc.zip)

**Comment by Enet4** [comment]
Thank you for reporting. This may be hiding a quirk in the parser around sequence and item delimiters, but for now it may indeed be best to raise a recoverable error when it reaches this supposedly illegal state. Will send in a PR soon.
